import SwiftUI

class Data: ObservableObject {
    @Published var providers: [ProviderDto] = [
        ProviderDto(
            title: "Volksbank Mittelhessen (...9433)", icon: "eurosign.bank.building",
            transactions: [
                TransactionDto(title: "Rewe Einkauf", amount: -45.90, date: Date().addingTimeInterval(-86400 * 1)),
                TransactionDto(title: "Netflix", amount: -13.49, date: Date().addingTimeInterval(-86400 * 2)),
                TransactionDto(title: "Buchhandlung", amount: -24.30, date: Date().addingTimeInterval(-86400 * 3)),
                TransactionDto(title: "Amazon", amount: -67.89, date: Date().addingTimeInterval(-86400 * 4)),
                TransactionDto(title: "Kino", amount: -12.00, date: Date().addingTimeInterval(-86400 * 5)),
                TransactionDto(title: "Mediamarkt", amount: -200.00, date: Date().addingTimeInterval(-86400 * 6)),
                TransactionDto(title: "Restaurant", amount: -45.00, date: Date().addingTimeInterval(-86400 * 7)),
                TransactionDto(title: "Spotify", amount: -9.99, date: Date().addingTimeInterval(-86400 * 8)),
                TransactionDto(title: "Tankstelle", amount: -60.00, date: Date().addingTimeInterval(-86400 * 9)),
                TransactionDto(title: "Gehalt", amount: 3453.50, date: Date().addingTimeInterval(-86400 * 9)),
                TransactionDto(title: "Zalando", amount: -80.45, date: Date().addingTimeInterval(-86400 * 10)),
                TransactionDto(title: "Supermarkt", amount: -25.78, date: Date().addingTimeInterval(-86400 * 11)),
                TransactionDto(title: "McDonalds", amount: -15.00, date: Date().addingTimeInterval(-86400 * 12)),
                TransactionDto(title: "IKEA", amount: -250.00, date: Date().addingTimeInterval(-86400 * 13)),
                TransactionDto(title: "H&M", amount: -50.00, date: Date().addingTimeInterval(-86400 * 14)),
                TransactionDto(title: "Ebay Kauf", amount: -12.99, date: Date().addingTimeInterval(-86400 * 15)),
                TransactionDto(title: "Apple Music", amount: -14.99, date: Date().addingTimeInterval(-86400 * 16)),
                TransactionDto(title: "Fitnessstudio", amount: -49.99, date: Date().addingTimeInterval(-86400 * 17)),
                TransactionDto(title: "Bäcker", amount: -7.50, date: Date().addingTimeInterval(-86400 * 18)),
                TransactionDto(title: "Friseur", amount: -30.00, date: Date().addingTimeInterval(-86400 * 19)),
                TransactionDto(title: "Online Bestellung", amount: -120.00, date: Date().addingTimeInterval(-86400 * 20)),
                TransactionDto(title: "Rewe Einkauf", amount: -45.90, date: DateComponents(calendar: .current, year: 2024, month: 12, day: 24).date!),
                TransactionDto(title: "Netflix", amount: -13.49, date: DateComponents(calendar: .current, year: 2024, month: 11, day: 20).date!),
                TransactionDto(title: "Buchhandlung", amount: -24.30, date: DateComponents(calendar: .current, year: 2024, month: 10, day: 10).date!),
                TransactionDto(title: "Amazon", amount: -67.89, date: DateComponents(calendar: .current, year: 2024, month: 9, day: 15).date!),
                TransactionDto(title: "Kino", amount: -12.00, date: DateComponents(calendar: .current, year: 2024, month: 8, day: 5).date!),
                TransactionDto(title: "Mediamarkt", amount: -200.00, date: DateComponents(calendar: .current, year: 2024, month: 7, day: 25).date!),
                TransactionDto(title: "Restaurant", amount: -45.00, date: DateComponents(calendar: .current, year: 2024, month: 6, day: 18).date!),
                TransactionDto(title: "Spotify", amount: -9.99, date: DateComponents(calendar: .current, year: 2024, month: 5, day: 10).date!),
                TransactionDto(title: "Tankstelle", amount: -60.00, date: DateComponents(calendar: .current, year: 2024, month: 4, day: 12).date!),
                TransactionDto(title: "Gehalt", amount: 3453.50, date: DateComponents(calendar: .current, year: 2024, month: 3, day: 30).date!),
                TransactionDto(title: "Zalando", amount: -80.45, date: DateComponents(calendar: .current, year: 2023, month: 12, day: 15).date!),
                TransactionDto(title: "Supermarkt", amount: -25.78, date: DateComponents(calendar: .current, year: 2023, month: 11, day: 8).date!),
                TransactionDto(title: "McDonalds", amount: -15.00, date: DateComponents(calendar: .current, year: 2023, month: 10, day: 20).date!),
                TransactionDto(title: "IKEA", amount: -250.00, date: DateComponents(calendar: .current, year: 2023, month: 9, day: 10).date!),
                TransactionDto(title: "H&M", amount: -50.00, date: DateComponents(calendar: .current, year: 2023, month: 8, day: 5).date!),
                TransactionDto(title: "Ebay Kauf", amount: -12.99, date: DateComponents(calendar: .current, year: 2023, month: 7, day: 18).date!),
                TransactionDto(title: "Apple Music", amount: -14.99, date: DateComponents(calendar: .current, year: 2023, month: 6, day: 22).date!),
                TransactionDto(title: "Fitnessstudio", amount: -49.99, date: DateComponents(calendar: .current, year: 2023, month: 5, day: 16).date!),
                TransactionDto(title: "Bäcker", amount: -7.50, date: DateComponents(calendar: .current, year: 2023, month: 4, day: 10).date!),
                TransactionDto(title: "Friseur", amount: -30.00, date: DateComponents(calendar: .current, year: 2023, month: 3, day: 8).date!),
                TransactionDto(title: "Online Bestellung", amount: -120.00, date: DateComponents(calendar: .current, year: 2023, month: 2, day: 15).date!),
            ],
            type: .debitCard
        ),
        ProviderDto(
            title: "Sparkasse (...4100)",
            icon: "eurosign.bank.building",
            transactions: [
                TransactionDto(title: "Spotify", amount: -9.99, date: Date().addingTimeInterval(-86400 * 1)),
                TransactionDto(title: "IKEA", amount: -150.00, date: Date().addingTimeInterval(-86400 * 2)),
                TransactionDto(title: "Burger Palace", amount: -14.95, date: Date().addingTimeInterval(-86400 * 3)),
                TransactionDto(title: "Zalando", amount: -100.50, date: Date().addingTimeInterval(-86400 * 4)),
                TransactionDto(title: "Rewe", amount: -35.20, date: Date().addingTimeInterval(-86400 * 5)),
                TransactionDto(title: "Mediamarkt", amount: -60.00, date: Date().addingTimeInterval(-86400 * 6)),
                TransactionDto(title: "Tankstelle", amount: -45.80, date: Date().addingTimeInterval(-86400 * 7)),
                TransactionDto(title: "Restaurant", amount: -30.00, date: Date().addingTimeInterval(-86400 * 8)),
                TransactionDto(title: "Netflix", amount: -13.49, date: Date().addingTimeInterval(-86400 * 9)),
                TransactionDto(title: "Amazon", amount: 200.00, date: Date().addingTimeInterval(-86400 * 10)),
                TransactionDto(title: "Ebay Kauf", amount: -20.00, date: Date().addingTimeInterval(-86400 * 11)),
                TransactionDto(title: "Steam", amount: -49.99, date: Date().addingTimeInterval(-86400 * 12)),
                TransactionDto(title: "H&M", amount: -40.00, date: Date().addingTimeInterval(-86400 * 13)),
                TransactionDto(title: "DM Drogerie", amount: -25.30, date: Date().addingTimeInterval(-86400 * 14)),
                TransactionDto(title: "Fitnessstudio", amount: -49.99, date: Date().addingTimeInterval(-86400 * 15)),
                TransactionDto(title: "McDonalds", amount: -8.50, date: Date().addingTimeInterval(-86400 * 16)),
                TransactionDto(title: "Lidl", amount: -12.45, date: Date().addingTimeInterval(-86400 * 17)),
                TransactionDto(title: "Burger King", amount: -14.90, date: Date().addingTimeInterval(-86400 * 18)),
                TransactionDto(title: "Kino", amount: -18.00, date: Date().addingTimeInterval(-86400 * 19)),
                TransactionDto(title: "Apple Store", amount: -999.00, date: Date().addingTimeInterval(-86400 * 20)),
                TransactionDto(title: "Rewe Einkauf", amount: -45.90, date: DateComponents(calendar: .current, year: 2024, month: 12, day: 24).date!),
                TransactionDto(title: "Netflix", amount: -13.49, date: DateComponents(calendar: .current, year: 2024, month: 11, day: 20).date!),
                TransactionDto(title: "Buchhandlung", amount: -24.30, date: DateComponents(calendar: .current, year: 2024, month: 10, day: 10).date!),
                TransactionDto(title: "Amazon", amount: -67.89, date: DateComponents(calendar: .current, year: 2024, month: 9, day: 15).date!),
                TransactionDto(title: "Kino", amount: -12.00, date: DateComponents(calendar: .current, year: 2024, month: 8, day: 5).date!),
                TransactionDto(title: "Mediamarkt", amount: -200.00, date: DateComponents(calendar: .current, year: 2024, month: 7, day: 25).date!),
                TransactionDto(title: "Restaurant", amount: -45.00, date: DateComponents(calendar: .current, year: 2024, month: 6, day: 18).date!),
                TransactionDto(title: "Spotify", amount: -9.99, date: DateComponents(calendar: .current, year: 2024, month: 5, day: 10).date!),
                TransactionDto(title: "Tankstelle", amount: -60.00, date: DateComponents(calendar: .current, year: 2024, month: 4, day: 12).date!),
                TransactionDto(title: "Gehalt", amount: 3453.50, date: DateComponents(calendar: .current, year: 2024, month: 3, day: 30).date!),
                TransactionDto(title: "Zalando", amount: -80.45, date: DateComponents(calendar: .current, year: 2023, month: 12, day: 15).date!),
                TransactionDto(title: "Supermarkt", amount: -25.78, date: DateComponents(calendar: .current, year: 2023, month: 11, day: 8).date!),
                TransactionDto(title: "McDonalds", amount: -15.00, date: DateComponents(calendar: .current, year: 2023, month: 10, day: 20).date!),
                TransactionDto(title: "IKEA", amount: -250.00, date: DateComponents(calendar: .current, year: 2023, month: 9, day: 10).date!),
                TransactionDto(title: "H&M", amount: -50.00, date: DateComponents(calendar: .current, year: 2023, month: 8, day: 5).date!),
                TransactionDto(title: "Ebay Kauf", amount: -12.99, date: DateComponents(calendar: .current, year: 2023, month: 7, day: 18).date!),
                TransactionDto(title: "Apple Music", amount: -14.99, date: DateComponents(calendar: .current, year: 2023, month: 6, day: 22).date!),
                TransactionDto(title: "Fitnessstudio", amount: -49.99, date: DateComponents(calendar: .current, year: 2023, month: 5, day: 16).date!),
                TransactionDto(title: "Bäcker", amount: -7.50, date: DateComponents(calendar: .current, year: 2023, month: 4, day: 10).date!),
                TransactionDto(title: "Friseur", amount: -30.00, date: DateComponents(calendar: .current, year: 2023, month: 3, day: 8).date!),
                TransactionDto(title: "Online Bestellung", amount: -120.00, date: DateComponents(calendar: .current, year: 2023, month: 2, day: 15).date!),
            ],
            type: .debitCard
        ),
        ProviderDto(
            title: "Deutsche Bank",
            icon: "eurosign.bank.building",
            transactions: [],
            type: .debitCard
        ),
        ProviderDto(
            title: "American Express Platinum Karte", icon: "creditcard",
            transactions: [
                TransactionDto(title: "Tankstelle", amount: -89.67, date: Date().addingTimeInterval(-86400 * 1)),
                TransactionDto(title: "Amazon Rückzahlung", amount: 220.00, date: Date().addingTimeInterval(-86400 * 2)),
                TransactionDto(title: "Fitnessstudio", amount: -49.99, date: Date().addingTimeInterval(-86400 * 3)),
                TransactionDto(title: "Restaurant", amount: -120.50, date: Date().addingTimeInterval(-86400 * 4)),
                TransactionDto(title: "DönerKönig", amount: -8.50, date: Date().addingTimeInterval(-86400 * 5)),
            ],
            type: .creditCard
        ),
        ProviderDto(
            title: "American Express Gold Karte", icon: "creditcard",
            transactions: [
                TransactionDto(title: "Zalando", amount: -120.99, date: Date().addingTimeInterval(-86400 * 1)),
                TransactionDto(title: "Apple Store", amount: -999.00, date: Date().addingTimeInterval(-86400 * 2)),
                TransactionDto(title: "Lokalmarkt Rückzahlung", amount: 15.50, date: Date().addingTimeInterval(-86400 * 3)),
                TransactionDto(title: "Bäckerei", amount: -5.00, date: Date().addingTimeInterval(-86400 * 4)),
            ],
            type: .creditCard
        ),
        ProviderDto(
            title: "Bank of Norwegian", icon: "creditcard",
            transactions: [
                TransactionDto(title: "EDEKA", amount: -45.60, date: Date().addingTimeInterval(-86400 * 1)),
                TransactionDto(title: "DM Drogerie", amount: -23.40, date: Date().addingTimeInterval(-86400 * 2)),
                TransactionDto(title: "Tankstelle", amount: -85.90, date: Date().addingTimeInterval(-86400 * 3)),
                TransactionDto(title: "McDonalds", amount: -12.30, date: Date().addingTimeInterval(-86400 * 4)),
            ],
            type: .creditCard
        ),
        ProviderDto(
            title: "PayPal", icon: "briefcase",
            transactions: [
                TransactionDto(title: "Ebay", amount: -120.50, date: Date().addingTimeInterval(-86400 * 1)),
                TransactionDto(title: "Netflix", amount: -15.99, date: Date().addingTimeInterval(-86400 * 2)),
                TransactionDto(title: "Twitch Donation", amount: -5.00, date: Date().addingTimeInterval(-86400 * 3)),
                TransactionDto(title: "Steam Kauf", amount: -49.99, date: Date().addingTimeInterval(-86400 * 4)),
                TransactionDto(title: "Etsy Verkauf", amount: 30.00, date: Date().addingTimeInterval(-86400 * 5)),
            ],
            type: .other
        ),
    ]
}
